<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260926120000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add user profile, email verification, and expiring authentication tokens.'; }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "user" ADD full_name VARCHAR(120) DEFAULT \'\' NOT NULL, ADD verified BOOLEAN DEFAULT TRUE NOT NULL');
        $this->addSql('CREATE TABLE auth_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, purpose VARCHAR(16) NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AUTH_TOKEN_USER ON auth_token (user_id)');
        $this->addSql('CREATE INDEX idx_auth_token_hash ON auth_token (token_hash)');
        $this->addSql('ALTER TABLE auth_token ADD CONSTRAINT FK_AUTH_TOKEN_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE auth_token DROP CONSTRAINT FK_AUTH_TOKEN_USER');
        $this->addSql('DROP TABLE auth_token');
        $this->addSql('ALTER TABLE "user" DROP full_name, DROP verified');
    }
}
